services:
  server:
    build:
      context: server
    image: thorium-server:latest
    ports:
      - "5000:5000"
    volumes:
      - ${EXPLOITS_DIR}:/exploits:rw
      - ${DATABASE_DIR}:/database:rw
      - ${STATS_DIR}:/stats:ro
  redis:
    image: redis:7.2.0-alpine
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "127.0.0.1:6379:6379"
  runner:
    build:
      context: runner
    image: thorium-runner:latest
    depends_on:
      - server
    restart: unless-stopped
    volumes:
      - ${EXPLOITS_DIR}:/exploits:rw
      - ${DATABASE_DIR}:/database:rw
      - ${STATS_DIR}:/stats:rw
      - ./config/runner:/app/config:rw
    environment:
      FLAG_REGEX: ${FLAG_REGEX}
      TICK_LENGTH_SECONDS: ${TICK_LENGTH_SECONDS}
  submission:
    build:
      context: submission
    depends_on:
      - redis
    restart: unless-stopped
    image: thorium-submission:latest
    volumes:
      - ${DATABASE_DIR}:/database:rw
      - ./config/submission:/app/config:rw
